Documentation/DocumentationAdmonition:
  Admonitions:
    - TODO
    - FIXME
    - BUG
    - OPTIMIZE
  Enabled: true
  Severity: Convention
# TODO: Address these issues and re-enable the check.

# Ignore false positives.
# See: https://github.com/crystal-ameba/ameba/issues/447
Lint/UselessAssign:
  Enabled: true
  Excluded:
    - src/spectator.cr
    - src/spectator/core/configuration.cr
    - src/spectator/core/runner.cr
    - src/spectator/core/source_cache.cr
    - spec/spectator/matchers/expect_spec.cr
