require "./expectation_partial"

module Spectator::Expectations
  # Expectation partial variation that operates on a block.
  struct BlockExpectationPartial(ReturnType) < ExpectationPartial
    # Actual value produced by calling the block.
    def actual
      @block.call
    end

    # Creates the expectation partial.
    # The label should be a string representation of the block.
    # The block is stored for later use.
    protected def initialize(@block : Proc(ReturnType), label, source_file, source_line)
      super(label, source_file, source_line)
    end

    # Creates the expectation partial.
    # The label is generated by calling to_s on the block.
    # The block is stored for later use.
    protected def initialize(@block : Proc(ReturnType), source_file, source_line)
      super(@block.to_s, source_file, source_line)
    end
  end
end
