require "./expectation_partial"

module Spectator::Expectations
  # Expectation partial variation that operates on a block.
  struct BlockExpectationPartial(ReturnType) < ExpectationPartial
    # Actual value produced by calling the block.
    def actual
      @block.call
    end

    # Creates the expectation partial.
    # The label should be a string representation of the block.
    # The block is stored for later use.
    protected def initialize(label : String, @block : -> ReturnType)
      super(label)
    end

    # Creates the expectation partial.
    # The label is generated by calling `#to_s` on the block.
    # The block is stored for later use.
    protected def initialize(@block : -> ReturnType)
      super(@block.to_s)
    end

    # Evaluates the expectation and returns it.
    private def eval(matcher, negated = false) : Expectation
      matched = matcher.match?(self)
      Expectation.new(matched, negated, self, matcher)
    end
  end
end
